"""add_performance_indexes

Revision ID: 3901d0463151
Revises: add_stock_quantity
Create Date: 2025-12-24 16:15:27.023263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3901d0463151'
down_revision: Union[str, None] = 'add_stock_quantity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'loyalty_points_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('1.00'))
    op.drop_constraint(op.f('businesses_slug_key'), 'businesses', type_='unique')
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
    op.drop_index(op.f('ix_loyalty_accounts_business_user'), table_name='loyalty_accounts')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_telegram_id'), 'orders', ['user_telegram_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.drop_constraint(op.f('promocodes_code_key'), 'promocodes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('promocodes_code_key'), 'promocodes', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_orders_user_telegram_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('ix_loyalty_accounts_business_user'), 'loyalty_accounts', ['business_id', 'user_telegram_id'], unique=True)
    op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.create_unique_constraint(op.f('businesses_slug_key'), 'businesses', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('businesses', 'loyalty_points_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('1.00'))
    # ### end Alembic commands ###

