xychart-beta
    title "Рост рынка электронной коммерции в России (млрд руб.)"
    x-axis [2019, 2020, 2021, 2022, 2023, 2024]
    y-axis "Объем рынка (млрд руб.)" 0 --> 5000
    bar [1800, 2500, 3200, 3800, 4200, 4800]
    ---
    config:
      themeVariables:
        xyChart:
          plotColorPalette: "#4C1D95"

