%%{init: {'theme':'base', 'themeVariables': { 'primaryColor':'#0088cc', 'primaryTextColor':'#fff', 'primaryBorderColor':'#006699', 'lineColor':'#0088cc', 'secondaryColor':'#5B21B6', 'tertiaryColor':'#6B46C1'}}}%%
pie title "Аудитория Telegram в России"
    "Активные пользователи" : 70
    "Потенциальные клиенты" : 30

